version: '3.8'

services:
  watchapp-service:
    build:
      context: ..

      dockerfile: src/Dockerfile
    container_name: watchapp_api
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:15
    container_name: watchapp_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: avnadmin
      POSTGRES_PASSWORD: AVNS_2shXhYvWfpf4TNn0SVc
      POSTGRES_DB: defaultdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avnadmin -d defaultdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: