# Çalıştırılacak servisleri tanımladığımız bölüm
services:
  # Servisimize bir isim veriyoruz: watchapp-builder
  watchapp-builder:
    # Bu servisin kullanacağı imajın adını belirtiyoruz.
    # Bu imaj, aşağıda belirttiğimiz şekilde yerel olarak oluşturulacak.
    image: denizbank-watchapp-builder
    # İmajın nasıl oluşturulacağını tarif ediyoruz.
    build:
      # Build context'i üst dizin olarak belirliyoruz (Android projesinin kök dizini).
      context: ..
      # Kullanılacak Dockerfile'ın yolunu belirtiyoruz.
      dockerfile: Dockerfile
    # Volume (Paylaşılan Klasör) Tanımlaması - EN ÖNEMLİ KISIM
    # Konteyner içinde üretilen dosyaları, kendi bilgisayarımızda da görebilmek için klasörleri eşleştiriyoruz.
    volumes:
      # Açıklaması:
      # BİLGİSAYARIMDAKİ_KLASÖR : KONTEYNER_İÇİNDEKİ_KLASÖR
      # Bilgisayarımdaki ./app/build klasörünü, konteyner içindeki /project/app/build klasörüne bağla.
      # Bu sayede, konteyner içinde APK oluşturulduğunda, dosya anında bizim bilgisayarımızdaki
      # ./app/build/ klasörüne de gelmiş olacak.
      - ./app/build:/project/app/build

